### ISSUE TITLE
接收数据有丢失

### ISSUE THREAD

**Issue by 276016439** [kai-morich/usb-serial-for-android-mik3y#1]
请教一下，我使用此驱动，在接收10ms一次的数据时，偶尔会出现数据丢失的问题，可能会是什么原因造成的？使用的是ch340模块，用pc上位机接收时不会丢失数据的

**Comment by tianminggh** [comment]
me too

**Comment by kai-morich** [comment]
please check: https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#I_observed_codereadcode_data_loss_with_continuous_transfer_at_high_baud_rates

**Comment by 276016439** [comment]
> please check: https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#I_observed_codereadcode_data_loss_with_continuous_transfer_at_high_baud_rates

Thank you very much, the problem has been solved

**Comment by tianminggh** [comment]
> > please check: https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#I_observed_codereadcode_data_loss_with_continuous_transfer_at_high_baud_rates
> 
> Thank you very much, the problem has been

> > please check: https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#I_observed_codereadcode_data_loss_with_continuous_transfer_at_high_baud_rates
> 
> Thank you very much, the problem has been solved

你改了哪里解决了呢？
